### PR TITLE
CHANGELOG.md

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
I translated all explanations from v1.0.0 and up. 
I thought is was too much to translate every single commit/minor. But if there are still some important parts left I'll dot those to.
Please review spelling/grammar since I'm not to great at it :neutral_face:

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
@iojs/iojs-nl review needed

**Comment by yoshuawuyts** [comment]
I'll look at it later tonight. Nice work! :tada:

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by timdp** [comment]
There are a few typos and grammatical errors we should correct. However, it's still a bit unclear to me which parts should be translated. Like you already mentioned, I definitely wouldn't go about translating the commit messages. So it's basically major changes and known issues then? Let's maybe add "(in English)" or "(Engels)" to the title of the commits section.

**Comment by yoshuawuyts** [comment]
Oh, it's super annoying that GH isn't showing a diff on this. To make it more easier to comment directly from the commit, can you squash these into a single commit? Thanks!

Oh and:
 `s/Opmerkelijke vernanderingen/Opmerkelijke veranderingen/`
`s/Opmerkelijke veraneringen/Opmerkelijke veranderingen/`

**Comment by AdriVanHoudt** [comment]
@timdp the problem is that the english and dutch parts run through each other a little bit. Maybe we could make a distilled dutch changelog with only the major stuff in it and link to the original for more detailed stuff
@yoshuawuyts I can try :P

**Comment by timdp** [comment]
@AdriVanHoudt Isn't the purpose of the weekly blog post to have a distilled changelog?

**Comment by AdriVanHoudt** [comment]
@timdp fair call, I'll close the PR for now, if it is ever requested we can get back to it

**Pull request closed without merging**
