### PR TITLE
readme: add faq

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Adds a small FAQ section with notes about how to join and what this is. Thanks!

### CODE REVIEW

**Comment by mikeal** [comment]
shouldn't this be in Dutch? :)

**Comment by yoshuawuyts** [comment]
I'm not sure. In Holland (not sure about BE / other countries) most, if not all communication happens in English (meetups included). I'd prefer to just do the actual content in Dutch, and keep the repo / communication around the repo in English. Feels weird to communicate in Dutch on GH, hah.

@timdp How do you feel about this?

**Comment by mikeal** [comment]
Wow, I had no idea :)

**Comment by timdp** [comment]
I prefer English as well. Personal sentiments aside, it's more transparent for the community this way. Basically, I'd only write the content we actually produce in Dutch, and keep everything else in English.

Incidentally, we might end up forking to a Dutch/Netherlands version and a Dutch/Belgium one. Personally, I quite like the Dutch, so I have no problem succumbing to their rhetoric for the time being. :)

**Comment by yoshuawuyts** [comment]
Okay, sounds like I can merge this then!

**Pull request merged**
