### PR TITLE
Added dutch explanation of faq

### PR DESCRIPTION
**Pull request by AdriVanHoudt**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Why are we adding this in Dutch? Imo only content should be localized, given that contributors should be bilingual anyway and having all docs in English improves transparency with the rest of the io.js i18n community. I'm -1 on this change.

**Comment by AdriVanHoudt** [comment]
See point 2 of #1
I do agree that most of the communication should be in english but if someone wants to ask something in dutch that person is welcome to here, that's (on of) the point(s) of this repo

**Comment by AdriVanHoudt** [comment]
Unless be description he just means the `io.js lokalisatie (i18n) in het Nederlands`

**Comment by yoshuawuyts** [comment]
@AdriVanHoudt yep, description is just that to me. I think we should still add links to the twitter / gmail so questions can indeed be asked. I view this repo to be more of a contributor thing than a 'post-your-questions-here-and-we'll-answer-them' kinda thing; gmail / twitter are for that imo.

**Comment by AdriVanHoudt** [comment]
+1 for twitter and gmail links and if @timdp agrees I'll close this PR

**Comment by timdp** [comment]
I'd expect most people who visit this repo to be adequately fluent in both Dutch and English. If that's not the case, I'd actually prefer English over Dutch, paradoxical as that may seem. We're not the Dutch support channel, we're the localization team.

**Comment by AdriVanHoudt** [comment]
Ok :+1:

**Pull request closed without merging**
